# Generated by Django 4.1.7 on 2023-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Ваша почта')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Ваш тел.номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.CharField(max_length=255, verbose_name='Ваш возраст')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователь',
            },
        ),
    ]
